[server]
headless = true
port = $PORT
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[theme]
base="light"
primaryColor="#0E76FD"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
