[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#0E76FD"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
